# This is an example filter config for tracked vehicle Absolem from Czech Technical University's
# VRAS team. The robot is equipped with a Realsense D435.
# The field of view of the sensor can only capture a few links, so the `only_links` parameter is set
# to increase performance. Also, the `filter/keep_clouds_organized` parameter is important here to
# retain the 2D structure of the RGBD camera output.
cloud_filter_chain:
  - name: RobotBodyFilter
    type: robot_body_filter/RobotBodyFilterPointCloud2
    params:
      frames/fixed: dual_arm
      frames/sensor: left_camera_link
      frames/filtering: left_camera_link
      frames/output: left_camera_link
      filter/keep_clouds_organized: True
      filter/do_clipping: True
      filter/do_contains_test: True
      filter/do_shadow_test: False
      sensor/point_by_point: False
      sensor/min_distance: 0.1
      sensor/max_distance: 5.0
      only_links: ["right_base_link", "right_shoulder_link", "right_bicep_link", "right_forearm_link", "right_spherical_wrist_1_link", "right_spherical_wrist_2_link", "right_bracelet_link", 
                    "right_end_effector_link", "right_camera_link", "right_tool_frame", 
                    "right_left_inner_finger",  "right_left_inner_finger_pad",  "right_left_inner_knuckle",  "right_left_outer_finger",  "right_left_outer_knuckle",
                    "right_right_inner_finger", "right_right_inner_finger_pad", "right_right_inner_knuckle", "right_right_outer_finger", "right_right_outer_knuckle"]
      body_model/inflation/scale: 1.05
      body_model/inflation/padding: 0.025
      body_model/robot_description_param: "/my_gen3_right/robot_description"
      transforms/buffer_length: 15.0
      transforms/timeout/reachable: 0.52
      transforms/timeout/unreachable: 0.52
      bounding_sphere/compute: False
      bounding_box/compute: False
      oriented_bounding_box/compute: False
      local_bounding_box/compute: False
      debug/pcl/inside: False
      debug/pcl/clip: False
      debug/pcl/shadow: False
      debug/marker/contains: False
      debug/marker/shadow: False

      bounding_sphere/compute: True
      bounding_sphere/debug: True
      bounding_sphere/marker: True
      bounding_sphere/publish_cut_out_pointcloud: True
      bounding_box/compute: True
      bounding_box/debug: True
      bounding_box/marker: True
      bounding_box/publish_cut_out_pointcloud: True